### ISSUE TITLE
version 0.9.0 has dropped PY2 support but is still installable

### ISSUE THREAD

**Issue by piotrek204** [inveniosoftware/dictdiffer#164]
Package version (if known): 0.9.0

## Describe the bug
According to 0.9.0 release notes, python < 3.5 is no longer supported, but is still possible to install the package in this version under python 2.7. In my case, this results in:

```
...\site-packages\dictdiffer\__init__.py", line 13, in <module>
    from collections.abc import (Iterable, MutableMapping, MutableSequence,
ImportError: No module named abc
```

## Steps to Reproduce
1. py -2 -m pip install dictdiffer==0.9.0
2. execute under PY2: `from dictdiffer import diff`

## Expected behavior
Metadata in the package should not allow installation under incompatible interpreter.

**Comment by markgras** [comment]
To elaborate on the "metadata in the package" referenced above, per the official [PyPA docs](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires):

> If your project only runs on certain Python versions, setting the `python_requires` argument to the appropriate PEP 440 version specifier string will prevent pip from installing the project on other Python versions.

This is a common developer oversight when dropping support for older Python versions. For example, I opened [a similar issue](https://github.com/grantjenks/python-diskcache/issues/160) for the `diskcache` project. After fixing the metadata, package versions with incorrect metadata should be yanked from PyPI. Otherwise the problem is not really resolved, as Python versions <3.5 will continue to install incorrect `dictdiffer` versions.
